### PR TITLE
adds a bunch of stuff

### PR DESCRIPTION
**Pull request by whiitehead**
Basically all the stuff I was talking about

### CODE REVIEW

**Comment by jleung51** [comment]
@CalebElliottWhitehead Could you please list out all the changes you made and why? It'll make it easier to review!

Also, please try to break changes into commits with useful messages, so you don't need to list everything in the pull request, and so we can refer back to the commit history in the future! :)

**Comment by whiitehead** [comment]
Hey, yeah sorry about that. I probably should have split this up into a few PRs. Basically, Ali and I's branches were pretty far ahead so I felt a bit like I should just rip the band-aid off

- Adds a class called Query that returns a request handler. can be used for all GET http methods
- Adds Entity super class. it holds the location so those methods only need to be written once. It also allows for type checking for the query class.
- Adds two GET methods to app.js for testing purposes
- Changes all files to lowercase for consistency. Capitalizing stateful class files was getting kinda weird.
- Moves game related files to "game" folder. Probably should have not included this in the pull request as it was mostly done for my own convenience, we should probably figure out a more thoughtful directory structure at some point.
- Lints all the files. Also probably should have made that a difference pull request.
- Deleted "database", Ali and I had replaced it with the game object awhile back and it wasnt being used any more and we hadnt got around to deleting it.

Yeah pretty ridiculous pull request but everything is now broken up into components so there shouldnt be any more massive pull requests like this any more. Also, you can leave it until the meeting and we can discuss it all there.

**Review by jleung51 — APPROVED** [review]
Looks good!

**Comment by jleung51** [comment]
Looks good. Thanks for the changes!

**Pull request merged**
